# Generated by Django 4.2 on 2024-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_Origin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country of Origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Min Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
