# Generated by Django 4.2 on 2024-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_country_of_origin_product_min_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Min Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Weight'),
        ),
    ]
