# Generated by Django 4.2 on 2024-06-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us Lists'},
        ),
    ]
